version: '3.9'

services:
  zookeepercp:
    image: confluentinc/cp-zookeeper:7.2.15
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "8023:2181"

  kafkabroker:
    image: confluentinc/cp-kafka:7.2.15
    depends_on:
      - zookeepercp
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeepercp:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092, PLAINTEXT_INTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:8021, PLAINTEXT_INTERNAL://kafkabroker:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "8021:9092"

  kafkaui:
    image: provectuslabs/kafka-ui:v0.7.2
    depends_on:
      - kafkabroker
    environment:
      KAFKA_CLUSTERS_0_NAME: processamento
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafkabroker:9094
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeepercp:2181
    ports:
      - "8022:8080"